server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: msvc-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      #webflux:
      routes:
      
       #swagger
        #products
        - id: msvc-products-swagger
          uri: lb://msvc-products
          predicates:
            - Path=/api/products/swagger-ui.html,/api/products/swagger-ui/**
          filters:
            - StripPrefix=1
        #orders
        - id: msvc-orders-swagger
          uri: lb://msvc-orders
          predicates:
            - Path=/api/orders/swagger-ui.html,/api/orders/swagger-ui/**
          filters:
            - StripPrefix=1
        #users
        - id: msvc-users-swagger
          uri: lb://msvc-users
          predicates:
            - Path=/api/users/swagger-ui.html,/api/users/swagger-ui/**
          filters:
            - StripPrefix=1
      
        - id: msvc-products
          uri: lb://msvc-products
          predicates:
            - Path=/api/products/**,/api/categories/**
          #filters:
          #  - StripPrefix=1
        - id: msvc-orders
          uri: lb://msvc-orders
          predicates:
            - Path=/api/orders/**,/api/orderItems/**
          #filters:
          #  - StripPrefix=1
        - id: msvc-users
          uri: lb://msvc-users
          predicates:
            - Path=/api/users/**
        - id: auth-service
          uri: lb://msvc-users
          predicates:
            - Path=/api/auth/**

        #openapi
        #products
#        - id: msvc-products-openapi
#          uri: lb://msvc-products
#          predicates:
#            - Path=/api/products/v3/api-docs/**,/api/products/api-docs/**
#          filters:
#            - StripPrefix=2
        #orders
#        - id: msvc-orders-openapi
#          uri: lb://msvc-orders
#          predicates:
#            - Path=/api/orders/v3/api-docs/**,/api/orders/api-docs/**
#          filters:
#            - StripPrefix=2
        #users
#        - id: msvc-users-openapi
#          uri: lb://msvc-users
#          predicates:
#            - Path=/api/users/v3/api-docs/**,/api/users/api-docs/**
#          filters:
#            - StripPrefix=2

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: users
        url: /api/users/api-docs
      - name: products
        url: /api/products/api-docs
      - name: orders
        url: /api/orders/api-docs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG

jwt:
  secret: aVeryLongSecretKeyThatIsAtLeast32Chars!!
  expiration: 900000 #15*1000*60 #15 minutes
