server:
  port: 8001

spring:
  datasource:
    url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres
    username: postgres.yhnqvpahxejfqltzzjxp
    password: B4$3d3d4t0$
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: product_schema
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis
      port: 6379
      timeout: 6000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false
  show-actuator: true

jwt:
  secret: aVeryLongSecretKeyThatIsAtLeast32Chars!!
  expiration: 900000 #15*1000*60 #15 minutes
