server:
  port: 8001

spring:
  datasource:
    url: jdbc:postgresql://db.yhnqvpahxejfqltzzjxp.supabase.co:5432/postgres
    username: postgres
    password: B4$3d3d4t0$
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: user_schema
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

jwt:
  secret: aVeryLongSecretKeyThatIsAtLeast32Chars!!
  expiration: 900000 #15*1000*60 #15 minutes
