server:
  port: 8001

spring:
  datasource:
    url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres
    username: postgres.yhnqvpahxejfqltzzjxp
    password: B4$3d3d4t0$
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: order_schema
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

kafka:
  topics:
    order-created: order.created
    stock-reserved: inventory.stock.reserved
    stock-failed: inventory.stock.failed

resilience:
  circuitbreaker:
    instances:
      products:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
  retry:
    instances:
      products:
        max-attemps: 3
        wait-duration: 200ms

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false
  show-actuator: true

jwt:
  secret: aVeryLongSecretKeyThatIsAtLeast32Chars!!
  expiration: 900000 #15*1000*60 #15 minutes
